#!/bin/sh
# decription: Control EManager as a Service
# chkconfig: 2345 99 99

# Source function library.
#. /etc/rc.d/init.d/functions
RETVAL=1
prog=EManager
start() {
        echo -n "Starting $prog: "
        $prog &
}
stop() {
        echo -n "Stopping $prog: "
	killall $prog
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
restart)
        stop
        start
        ;;
*)
        echo "Usage: $0 { start | stop | restart}"
        RETVAL=1
        ;;
esac
exit $RETVAL

